# Generated by Django 5.2.17 on 2026-09-10 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("connections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RawItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="Unique identifier from provider source (e.g. entry guid/id or message id)",
                        max_length=512,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("news", "News"),
                            ("email", "Email"),
                            ("pr", "Pull Request"),
                            ("event", "Event"),
                            ("bill", "Bill / Invoice"),
                        ],
                        default="news",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("body_snippet", models.TextField(blank=True, default="")),
                ("author", models.CharField(blank=True, default="", max_length=255)),
                (
                    "source_url",
                    models.URLField(blank=True, default="", max_length=1024),
                ),
                ("received_at", models.DateTimeField(db_index=True)),
                ("is_important", models.BooleanField(blank=True, null=True)),
                ("is_spam", models.BooleanField(default=False)),
                ("feedback_score", models.FloatField(default=0.0)),
                (
                    "dedup_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hash ensuring idempotency and deduplication",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_items",
                        to="connections.connection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "received_at"],
                        name="ingestor_ra_user_id_a8ac37_idx",
                    ),
                    models.Index(
                        fields=["connection", "received_at"],
                        name="ingestor_ra_connect_16db0d_idx",
                    ),
                    models.Index(
                        fields=["dedup_hash"], name="ingestor_ra_dedup_h_51ad95_idx"
                    ),
                ],
            },
        ),
    ]
