# Generated by Django 5.2.17 on 2026-09-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawitem",
            name="section_hint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional section routing hint (e.g. 'money' or 'actions')",
                max_length=32,
            ),
        ),
    ]
