# Generated by Django 5.2.17 on 2026-09-19 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_key",
                    models.CharField(
                        db_index=True,
                        help_text="Identifier for category, provider, topic, or section",
                        max_length=64,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=0.0,
                        help_text="Relative affinity weight (-10.0 to +10.0)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_weights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-weight"],
                "unique_together": {("user", "category_key")},
            },
        ),
    ]
