# Generated by Django 5.2.17 on 2026-09-10 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("rss", "RSS Feed"),
                            ("github", "GitHub"),
                            ("gmail", "Google Gmail"),
                            ("telegram", "Telegram"),
                        ],
                        default="rss",
                        max_length=32,
                    ),
                ),
                (
                    "external_account",
                    models.CharField(
                        help_text="Feed URL, account email, or external identifier",
                        max_length=512,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="User-friendly label for this connection",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this connection is actively polled during scheduled ingestion",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when entries were last fetched successfully",
                        null=True,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Details of the most recent fetch error, if any",
                    ),
                ),
                (
                    "encrypted_token",
                    models.TextField(
                        blank=True,
                        help_text="OAuth access/refresh token or secret (if applicable)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "provider", "external_account")},
            },
        ),
    ]
