# Generated by Django 5.2.17 on 2026-09-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Profile avatar URL from OAuth provider",
                max_length=1024,
            ),
        ),
    ]
