# Generated by Django 5.2.17 on 2026-09-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0002_connection_avatar_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="provider",
            field=models.CharField(
                choices=[
                    ("rss", "RSS Feed"),
                    ("github", "GitHub"),
                    ("gmail", "Google Gmail"),
                    ("telegram", "Telegram"),
                    ("calendar", "Google Calendar"),
                ],
                default="rss",
                max_length=32,
            ),
        ),
    ]
