# Generated by Django 5.2.17 on 2026-09-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="digest",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Audit metadata including skipped spam items and ranking decisions",
            ),
        ),
    ]
