# Generated by Django 5.2.17 on 2026-09-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digest", "0002_digest_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="digest",
            name="delivery_channels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Channels to which this digest has been or will be delivered",
            ),
        ),
        migrations.AddField(
            model_name="digestitem",
            name="is_adjusted_by_weight",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether this item's ranking was shifted by user category weights",
            ),
        ),
    ]
