# Generated by Django 5.2.17 on 2026-09-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digest", "0003_digest_delivery_channels_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digest",
            name="delivery_channels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="digest",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="digestitem",
            name="section",
            field=models.CharField(
                choices=[
                    ("actions", "Action Items"),
                    ("emails", "Important Emails"),
                    ("money", "Money Watch"),
                    ("news", "Technology & World News"),
                    ("events", "Calendar & Scheduled Events"),
                ],
                default="news",
                max_length=32,
            ),
        ),
    ]
